apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: whoami-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami-container
          image: traefik/whoami:v1.10
          ports:
            - containerPort: 80