apiVersion: v1 # Specifies the API version for the Secret resource.
kind: Secret # Defines the resource type as Secret.
metadata:
  name: mongo-secret # The name of the Secret, used to reference it.
type: Opaque # The Secret type 'Opaque' indicates arbitrary user-defined data.
data:
  mongo-user: YWRtaW4=  # The base64 encoded username. In this example, 'admin' is encoded.
  mongo-password: cGFzc3dvcmQ=  # The base64 encoded password. In this example, 'password' is encoded.

# Overview:
# - This Secret named 'mongo-secret' stores credentials for MongoDB.
# - Contains two pieces of data: 'mongo-user' and 'mongo-password'.
# - Values are base64 encoded to meet Kubernetes encoding requirements for Secret objects.
# - Used to securely inject credentials into MongoDB pods without hardcoding them.
